### PR TITLE
Fixed: Weld created memory leak not added to undo list

### PR DESCRIPTION
**Pull request by dvdvideo1234**
Added: HB entity hover on props option
Added: Entity setup that integrates sane borders for HB parameters
Added: `UpdateFilter` To automatically populate trace filter for `detect props`
Changed: `UpdateMask` us now shared to be used on CL traces
Optimized: Trace filters can now ,use entity list which is faster
Optimized: `UpdateDecimals` now returns text width

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
Will try to test today

**Comment by dvdvideo1234** [comment]
[gm_flatgrass 2023-9-20 14-55-21.webm](https://github.com/Sony-dev/Offset-Hoverballs/assets/9112662/ca280087-1274-4aee-bc76-f65ef6295a89)

**Comment by Sony-dev** [comment]
Spent a while testing this, you've made some really good improvements in here!
Hovering over props is very cool, I remember Marum talking about not being able to implement it into their original version.
And support for translations is always good, though we might have to rely on community contributions for those.
Bit confused about the hover UI though, it looks like you've reverted the width scaling back to the old method with the overlapping text issue?

**Comment by dvdvideo1234** [comment]
Ahh, maybe sorry about that... I never noticed. Thank you for pointing that out!

**Pull request merged**
