### PR TITLE
Apply: Automatic validation for translation files

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
More about the automatic validator here: https://github.com/dvdvideo1234/ZeroBraineProjects/tree/master/GmodLangResource

Whenever you are ready @Sony-dev

**Comment by Sony-dev** [comment]
Oh I see, This automatic validator is something you run manually to check the resource files are ok, not part of the actual addon code?
Was confused about the "^M" at the end of each line of the translations, but I think that's just the git diff being weird.

**Comment by Sony-dev** [comment]
I also see you've set `["spawnmargin"] = "0",` in this version. Would having this be 1 by default not be more familiar for new users as then it works the same way as the default hoverball tool?

**Comment by dvdvideo1234** [comment]
Yeah. CTRL-M is usually displayed by `github` when `UTF-8` character set is commuted into the repository
Ah, that is the case then. It's because I saw the original translation abbrevs are labeled:
```lua
--EN
tool.offset_hoverball.spawnmargin=Spawn margin
tool.offset_hoverball.spawnmargin_tt=Sets how far the hoverball is offset from the spawn surface.\nDefaults to 0.
--BG
tool.offset_hoverball.spawnmargin=Разстояние при създаване
tool.offset_hoverball.spawnmargin_tt=Задава на какво разстояние ховърболът да бъде отместен от повърхността при създаване.\nПо подразбиране е 0.
```
It insists on the default value being 1, but I guess it is up to you. I thing it would rather be consistent with the tool-tip or you have something else in mind ?

**Comment by Sony-dev** [comment]
Ah, I must have thought 0 was the same as the default hoverball when doing the tooltips, My bad!
I think defaulting to 1 would be good for both consistency with the default tool and being friendly to new users.
They could always change it later if they prefer.

I should probably update the Steam release to the improved version also, the last update was a while ago.
I don't think we have any bugs that would cause problems?

**Comment by dvdvideo1234** [comment]
From this PR it is mainly Bulgarian translation, so none that I know of. You can adjust the default
value of `["spawnmargin"] = "1",` in the tool configuration and also the translations:
> ```lua
> --EN
> tool.offset_hoverball.spawnmargin=Spawn margin
> tool.offset_hoverball.spawnmargin_tt=Sets how far the hoverball is offset from the spawn surface.\nDefaults to 0.
> --BG
> tool.offset_hoverball.spawnmargin=Разстояние при създаване
> tool.offset_hoverball.spawnmargin_tt=Задава на какво разстояние ховърболът да бъде отместен от повърхността при създаване.\nПо подразбиране е 0.
> ```

**Pull request merged**
