### PR TITLE
Positioning changes and remove data duplication

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
image

**Comment by dvdvideo1234** [comment]
image

**Comment by dvdvideo1234** [comment]
image

**Comment by dvdvideo1234** [comment]
image

**Comment by dvdvideo1234** [comment]
Done, @Sony-dev now the tool uses OBB surfcae

**Comment by Sony-dev** [comment]
Positioning using half the size of the ball doesn't look quite right, most models just get stuck in the target prop.
Ideally the user shouldn't need to unweld and adjust the positioning after placing each hoverball.
Maybe we should keep the offsets the same as the default hoverball tool for consistency?

**Comment by Sony-dev** [comment]
gmod_2023-09-23_00-39-46

**Comment by dvdvideo1234** [comment]
I coded a margin. It is by default 1 ( one time offset by prop half-width on the trace hit normal ). 
image
When 1 it works normal, zero half of the prop is inside trace entity ( `OBB` is located at `trace.HitPos` ), -1 whole prop and so on..

**Pull request merged**
