### PR TITLE
Drawing the same character outside of the loop

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
Do you think we can make the same thing for `MouseoverUI_HeaderKeys` and `MouseoverUI_LabelKeys` and do not call translations every frame ?

**Comment by Sony-dev** [comment]
> Do you think we can make the same thing for `MouseoverUI_HeaderKeys` and `MouseoverUI_LabelKeys` and do not call translations every frame ?

Something kind of like this?
https://github.com/Sony-dev/Offset-Hoverballs/tree/translation-changes

I have no idea if doing it this way is actually more efficient or not.
I'd imagine the built-in "#tool.translate.whatever" system uses cached results instead of looking it up every frame anyway.
(At least I really hope it does considering it is used everywhere in gmod)

**Comment by dvdvideo1234** [comment]
@Sony-dev 

Yes, sir.. Exacctly: https://github.com/Sony-dev/Offset-Hoverballs/commit/73edbd2e73a0f0f629cbf169b1d6292816128b94 :P

**Comment by dvdvideo1234** [comment]
The linked commit will update the needed things. This PR is not needed

**Pull request closed without merging**
