### PR TITLE
Better dynamic translations  support

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
image

**Comment by dvdvideo1234** [comment]
Hey, there @Sony-dev 

I see the different models have their positions in different locations relative to the models themselves.
image

So using `ball:SetPos()` will result in displacement when the entity is spawned. I see we use  [`phys:ApplyForceCenter(vforce)`](https://wiki.facepunch.com/gmod/PhysObj:ApplyForceCenter) which forces the center upwards and also [`self:WorldSpaceCenter()`](https://wiki.facepunch.com/gmod/Entity:WorldSpaceCenter) to calculate lasers where both work form the center. In this case we can use [`EBB`](https://wiki.facepunch.com/gmod/Entity:OBBCenter) which is available on the server and client and it will work if the user try to shove a model that does not have collisions. How does this solution sound to you ?

**Comment by dvdvideo1234** [comment]
1. We should not use  `sbox_maxoffset_hoverball` but instead `sbox_maxoffset_hoverball-S`. See below
https://github.com/search?q=repo%3AFacepunch%2Fgarrysmod%20hoverball&type=code
2. It will be also better to use `tool.offset_hoverball.*` instead of `gui.info.offset_hoverball.*` to use less translation definitions. These that are shown are linked to the entity created anyway.

**Comment by Sony-dev** [comment]
Ah, good catch! I usually don't use those models so never noticed the laser and force trace don't line up.
Yeah using OBBCenter() does seem like a good solution to keep everything consistent.
(The helpful image is appreciated also)

I am very confused about the changes to GetLongest though. Looking at the code I actually have no idea what it does.
The original function was from my utils library and is probably more complex than is needed for this use. (And ended up only being called once)

I also see that I've managed to mess up the spawned entity being aligned with the tool ghost, Will have a fix for that shortly. Whoops

**Comment by dvdvideo1234** [comment]
You can leave the OBB center alignment and getting rid of `gui.info.offset_hoverball.*` to me then. I see this is duplicated information and on the tool panel ( generally sliders ) the same value is used:
```
tool.offset_hoverball.air_resistance=Air Resistance
gui.info.offset_hoverball.air_resistance=Air resistance:
```
We can simply use `tool.offset_hoverball.air_resistance` and append `:` to become like this anyway
```
tool.offset_hoverball.air_resistance=Air Resistance
```
I changed the function `GetLongest`, so it can be used to order anything custom on a specified criteria by
making a function argument and injecting the manipulated references via the `act` argument. Currently I am using it to get the longest string from 3 sets of data ( translated `TableOHBInf`, translated `HeaderStr` and the formatted internal value ). I will always prefer to do many things in one pass:
```lua
	SizeX = TableOHBInf.W + 30 + GetTextSizeX("OHBTipFontSmall",
		GetLongest(TableOHBInf, nil, nil, nil, -- Process and get the longest
			function(t, i, r, k, v) -- For each parameter being displayed run routine
				local idx = t[i].ID -- Obtain the source data index to read the value
				local str = DecFormat:format(HBData[idx]) -- Format decimals
				HBData[idx] = str; return str -- Return the string being compared
			end))
```
It will basically format all of the internal values, see which one is the longest to pass to `GetTextSizeX` by manually injecting data sets from `HBData` and using `TableOHBInf` as configuration to process it correctly. Finally retrieve its size and add it to `SizeX`.
1. Store and compare formatted values of `HBData[idx]`  ( 2..n )
2. Pass the longest found to `GetTextSizeX`
3. Use the return value and cached `TableOHBInf.W` to adjust the `SizeX`

**Pull request merged**
